### PR TITLE
New po files from Crowdin. Add buildwin files and a gitignore

### PR DESCRIPTION
**Pull request by Hakansv**
Rick.
The pot file don't need an update. No real changes made since last update to Crowdin.
I changed potfile.in to reflect the code. and also deleted the copy.
I'd to add some buildwin files to be able to build for a test of the mo files creation.

### CODE REVIEW

**Comment by Hakansv** [comment]
Rick.
That Travis fail seems not connected to my changes?

**Comment by rgleason** [comment]
No its not, just me. Looking at merge now.

**Comment by rgleason** [comment]
Thanks. Hakan

**Comment by Hakansv** [comment]
My repo copy is from your Git so nothing changed there.
The gitignore is to avoid Git comments about the build files and stuff.

**Pull request merged**
