### PR TITLE
Remove legacy dependencies, update opencpn-libs

### PR DESCRIPTION
**Pull request by sebastien-rosset**
This is an attempt to address this comment: https://github.com/OpenCPN/OpenCPN/pull/4265#issuecomment-2544556292

1. Remove `libs` directory.
2. In `.gitmodules`, use `https://github.com/OpenCPN/opencpn-libs.git` instead of the older `https://github.com/leamas/opencpn-libs.git`
3. Update `PKG_API_LIB` from `api-17` to `api-19`

I'm not really sure what needs to be done to modernize the plugin. The repo seems to have a mix of old way and new way using sub-modules.

### CODE REVIEW

**Comment by rgleason** [comment]
Many errors, not promising outcome.

need api-119?

For example

```
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:40 (add_subdirectory):
  add_subdirectory given source "opencpn-libs/api-19" which is not an
  existing directory.


CMake Error at CMakeLists.txt:54 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.


-- Building for target:release debian-wx32-arm64:11
-- Selected upload repository: o p e n c p n / v d r - a l p h a 
-- Configuring incomplete, errors occurred!
See also "/ci-source/build-debian/CMakeFiles/CMakeOutput.log".

```

**Comment by sebastien-rosset** [comment]
I initially had the same build errors in my workspace. The previous version was still cached. I deleted the entire directory, clone again, and it worked. Is there some caching in the CI?

**Comment by rgleason** [comment]
Now, I realize that opencpn-libs  needs to be updated.
So I guess I have to pull it down locally and issue an update set of commands.
The push it back up?
 
But does updated opencpn-libs  now have api-119? - I have not been following this very much.

> add_subdirectory given source "opencpn-libs/api-19" which is not an
>   existing directory.

**Comment by rgleason** [comment]
@sebastien-rosset   What would you suggest be done?

**Comment by sebastien-rosset** [comment]
> @sebastien-rosset What would you suggest be done?

Let me split in two parts:
1. PR to remove legacy dependencies.
2. PRs to upgrade to API 1.19

**Pull request merged**
